### ISSUE TITLE
Changes and incomplete IF statements

### ISSUE THREAD

**Issue by KAnon20** [ThePython10110/SpawnCraft#1]
Several if statements lack the text ", true" and thus deprive players of the ability to craft the spawn eggs.
Lines: 909, 916, 922, and (all pillager variants) 1063-1235.

Enderman and Creepers have been renamed or changed for reasons in VoxeLibre (formerly Mineclone 2). They are Rover and Stalker respectively, mobs_mc:rover (Line: 247) mobs_mc:stalker (Line: 280).
This might only be for VoxeLibre so it might require a workaround;
1. Will Aliasing mobs_mc:rover to mobs_mc:enderman and mobs_mc:stakjer to mobs_mc:ceeper work? I didn't try.
2. An if statement early in the .lua to check version and set variables to mobs_mc:enderman or mobs_mc:rover respectively.
3. An extra if statement at the line of code to select the proper spawn egg based on game version.

**Comment by ThePython10110** [comment]
This was my first Minetest mod. I was completely new to the API and also Lua. I'm not at all surprised I got things wrong. I'll probably fix all this soon.
